apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngrok-ingress-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngrok-ingress-controller-manager-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller-manager
  namespace: default