apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ngrok-ingress-controller-leader-election-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ngrok-ingress-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller-manager
  namespace: default